### ISSUE TITLE
Every time IDE starts a popup about plugin shows up

### ISSUE THREAD

**Issue by JacekAndrzejewski** [AprilViolet/highlight-bracket-pair#1]
As in title, each time I start Phpstorm a popup shows up.

PhpStorm 2021.2

![obraz](https://user-images.githubusercontent.com/29729811/129002687-63d874b6-9a1b-48e9-9b13-e56c551ab3be.png)

**Comment by AprilViolet** [comment]
@JacekAndrzejewski 
The new version v1.0.1 has been updated to the marketplace.
The logic of the pop-up window should be that when the plug-in is installed for the first time or the plug-in is updated to the version, the prompt will pop up.

**Comment by JacekAndrzejewski** [comment]
Works perfectly, thanks!
