### ISSUE TITLE
There is no default color configuration.

### ISSUE THREAD

**Issue by swebcc** [AprilViolet/highlight-bracket-pair#11]
There is no default color configuration.
![QQ图片20211109105158](https://user-images.githubusercontent.com/33777919/140853263-bce29645-ba84-4c84-9e92-4a1cb124ac24.png)

**Comment by AprilViolet** [comment]
@swebcc Thank you for your report, I will fix this problem and it will be fixed in the next version.

**Comment by AprilViolet** [comment]
@swebcc Hi, the new version v1.3.2 has been approved.The default color should already be in effect. Of course, you can modify it.
