### ISSUE TITLE
Incompatible with CLion 2021.3 Beta build 213.5744.5

### ISSUE THREAD

**Issue by bccox** [AprilViolet/highlight-bracket-pair#12]
Here's the pugin error I get from CLion:

> Plugin 'HighlightBracketPair' (version '1.3.1') is not compatible with the current version of the IDE, because it requires build 213 or older but the current build is CL-213.5744.5

**Comment by AprilViolet** [comment]
@bccox Thank you for your report, I will go back and fix it in the next version.Maybe I will wait until Idea2021.3GA to update, it will not take long

**Comment by AprilViolet** [comment]
@bccox Hi, the new version v1.3.2 has been approved.
