### ISSUE TITLE
I can't find it in marketplace

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [AprilViolet/highlight-bracket-pair#13]
EDIT: probably because it is not compatible with the latest IDEA version.

**Comment by AprilViolet** [comment]
@JavierSegoviaCordoba Thank you for your feedback, I will post a new version of the new version of Idea2021.3 before weekends.

**Comment by AprilViolet** [comment]
@JavierSegoviaCordoba Hi, the new version v1.3.2 has been approved.
