### ISSUE TITLE
gutter 无法显示括号对

### ISSUE THREAD

**Issue by PromiseNev** [AprilViolet/highlight-bracket-pair#15]
![image](https://user-images.githubusercontent.com/16667188/147225640-2c2939e4-e433-428c-b123-bf3b40696733.png)

![image](https://user-images.githubusercontent.com/16667188/147225762-8ea6e0cf-4d8d-4d91-b74c-58203996a2a4.png)
![image](https://user-images.githubusercontent.com/16667188/147225791-7b625256-9a60-41ec-ad86-7d37ab73753e.png)

都按照这个设置了,还是没有 括号对

**Comment by AprilViolet** [comment]
@PromiseNev 
emm暂时没有复现，这样设置应该是没有问题的
![image](https://user-images.githubusercontent.com/40155496/147242678-8f518851-1a0e-4680-a501-c788d1128f1d.png)


鼠标需要在大括号内才可以生效
另外问下你这演示的语言是?kotlin?有可能是语言支持的问题

**Comment by PromiseNev** [comment]
@AprilViolet   谢谢回复, 我是scala代码, 在mac下的idea 可以显示出来配对, 但是win 的idea不行,因为我win 用的...社区版的idea吗?那也不可能吧...我Mac也是社区版的idea

**Comment by AprilViolet** [comment]
@PromiseNev mac下可以显示，win下不能显示，还有这种事情...我目前在idea中安装scala插件写scala代码是可以显示的，不过还没有安装scala的SDK，后面我会再试下看能不能复现

**Comment by PromiseNev** [comment]
@AprilViolet  真的有....我甚至直接把idea的设置,导出,然后在win导入,都不行,这个问题应该可以复现

**Comment by AprilViolet** [comment]
@PromiseNev 我安装了scala3的环境，并且在idea2021.3中测试了，目前没有发现问题哦。我需要更多的信息让我能够复现，否则我这边也不好修改问题。
![Snipaste_2021-12-27_14-36-34](https://user-images.githubusercontent.com/40155496/147442287-c3ba2225-cb9a-4474-b1a2-947eadb6c156.png)

**Comment by PromiseNev** [comment]
![image](https://user-images.githubusercontent.com/16667188/147462873-b50b8743-2d08-407a-be4b-b6f5b504d416.png)
@AprilViolet  谢谢测试, 这是我所有安装的插件,测试了下,好像不是这些影响的我的scala 环境是2,12.10, idea 版本是IntelliJ IDEA 2021.3 (Community Edition)

**Comment by PromiseNev** [comment]
如果需要更多其他信息,我还可以提供,比如设置之类的,我刚才在设置里,搜gutter,没有太多的设置项

**Comment by AprilViolet** [comment]
@PromiseNev 本来以为是Community Edition版本的原因，现在来看并不是。应该也不是其它插件的影响，你的这些插件我都有安装，没有什么问题。
目前先建议卸载插件然后重新安装一下，创建一个新项目，试下是否有效？
![image](https://user-images.githubusercontent.com/40155496/147542593-c097d844-3a48-44e9-9476-d6cecff394c8.png)

**Comment by PromiseNev** [comment]
![image](https://user-images.githubusercontent.com/16667188/147564635-7ed40538-1361-470d-8018-4661b0c0a5f7.png)
我崩溃了, 我把idea 卸载掉, 用户名下的appdata idea的文件也删掉了(等于新环境了) 然后...就装了个scala插件,然后...还不行.fk

**Comment by PromiseNev** [comment]
@AprilViolet  我终于找到问题了,我这两天,把idea 全部卸载掉,清空,重装 重新拉项目...终于...找到原因了
![image](https://user-images.githubusercontent.com/16667188/147637307-a6e47707-db3e-4220-bcf4-6c34d8911dc1.png)
这个字体默认是12大小,我嫌太小了,然后改成14, 代码这边,就没有了,然后恢复成12,或者取消勾选,配对括号就出来了

**Comment by AprilViolet** [comment]
@PromiseNev 找到了就好，我刚想猜测会不会是字体大小的问题，看你已经设置了字体大小14，应该不会太小，想不到还是字体原因。这个原来还和系统默认字体有关系，这个我后面看能不能调节一下。

**Comment by PromiseNev** [comment]
@AprilViolet   血与泪啊,折腾了一天,把配置全删掉,idea重新装,挨个测试....才发现的
