### ISSUE TITLE
Not compatible

### ISSUE THREAD

**Issue by marcelloinfoweb** [AprilViolet/highlight-bracket-pair#21]
Plugin 'HighlightBracketPair' (version '1.3.4') is not compatible with the current version of the IDE, because it requires build 221.* or older but the current build is PS-222.3345.21

**Comment by AprilViolet** [comment]
@marcelloinfoweb 
Thanks for pointing out. 
The new version of idea will require jdk17. 
I will rebuild the plug-in in the new version of GA. please look forward to it.

**Comment by AprilViolet** [comment]
v1.3.5 is already compatible with IDEA2022.2.
