### ISSUE TITLE
1.3.5 compatibility issue

### ISSUE THREAD

**Issue by HarkTu** [AprilViolet/highlight-bracket-pair#22]
by mistake auto updated without reading update notes. new version is not compatible with 2022.1

**Comment by AprilViolet** [comment]
@HarkTu 
Yes, GitHub action reports an error. As a result, there is no update. The plug-in has been uploaded manually, and v1.3.5 has been approved. I will fix action on the weekend.

**Comment by AprilViolet** [comment]
@HarkTu Has been fixed in v1.3.6.
