### ISSUE TITLE
xml中不要这

### ISSUE THREAD

**Issue by tajudje4896545gvan1** [AprilViolet/highlight-bracket-pair#32]
![1](https://github.com/AprilViolet/highlight-bracket-pair/assets/135719560/9a51f7ce-c90a-479e-a309-a78d7deeba41)
在pom文件中，我不需要高亮， 而且这个高亮，看不清楚了

**Comment by AprilViolet** [comment]
前段时间繁忙，好，我加个设置选择值吧

**Comment by mathisgauthey** [comment]
> I was busy some time ago, okay, let me add a setting selection value.

Hey there, any update on this one ? Just found out this behavior came from this plugin, loving it otherwise but would love to disable it on XML tags and such o/

**Comment by AprilViolet** [comment]
> > I was busy some time ago, okay, let me add a setting selection value.
> 
> Hey there, any update on this one ? Just found out this behavior came from this plugin, loving it otherwise but would love to disable it on XML tags and such o/
> 
> EDIT: Found out one could disable the `Background` color of the `CuspBracket` :

---
[highlight-bracket-pair-1.5.0.zip](https://github.com/user-attachments/files/15807194/highlight-bracket-pair-1.5.0.zip)
+ Hello, this is the latest package. You can test whether it works properly. Unzip it and install it from disk
+ If it works, I will publish it to JetBrains Marketplace.
![image](https://github.com/AprilViolet/highlight-bracket-pair/assets/40155496/f92036bb-e3a5-49b1-bd0b-47de692c5856)
