### ISSUE TITLE
Plugin needs to be updated

### ISSUE THREAD

**Issue by lukeb2e** [AprilViolet/highlight-bracket-pair#36]
Hey - I just received the following error after trying to setup a new instance of my IDE.

```
Plugin 'HighlightBracketPair' (version '1.5.2') is not compatible with the current version of the IDE, because it requires build 242.* or older but the current build is IU-243.12818.47
```

**Comment by AprilViolet** [comment]
@lukeb2e v1.5.3 has been released, please try it.

**Comment by lukeb2e** [comment]
Sorry that I could only test now. I was on leave for a few days. 
The update works, thank you :)
